# Generated by Django 3.2 on 2021-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dna',
            options={'verbose_name_plural': 'DNAs'},
        ),
        migrations.AlterModelOptions(
            name='simiosxhumanos',
            options={'verbose_name_plural': 'Simios x Humanos'},
        ),
        migrations.AlterField(
            model_name='dna',
            name='dna',
            field=models.CharField(max_length=255),
        ),
    ]
